/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 rim.glb --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/rim-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Body1.geometry} material={nodes.Body1.material} />
    </group>
  )
}

useGLTF.preload('/rim-transformed.glb')
